export type Vehicle = {
  id: string;
  stock: string;
  year: number;
  make: string;
  model: string;
  trim?: string;
  price: number;
  downPayment?: number;
  monthlyPayment?: number;
  mileage?: number;
  engine?: string;
  transmission?: string;
  drivetrain?: string;
  bodyStyle?: string;
  fuel?: string;
  exteriorColor?: string;
  color?: string;
  vin?: string;
  interiorColor?: string;
  titleStatus?: string;
  owners?: number;
  accidentHistory?: string;
  features?: string[];
  financingAvailable?: boolean;
  shippingAvailable?: boolean;
  carfaxAvailable?: boolean;
  images: {
    exterior: string[];
    interior: string[];
  };
  featured?: boolean;
};

export const vehicles: Vehicle[] = [
  {
    id: "7",
    stock: "DA-1102",
    year: 1996,
    make: "Mazda",
    model: "B3000",
    trim: "SE Cab Plus",
    price: 1500,
    downPayment: 400,
    mileage: 46600,
    engine: "3.0L V6",
    transmission: "Automatic (4-Speed)",
    drivetrain: "RWD",
    fuel: "Gasoline",
    exteriorColor: "Pumice Metallic",
    color: "Pumice Metallic",
    interiorColor: "Beige",
    images: {
      exterior: ["/madza/ext.jpg", "/madza/ext2.jpg"],
      interior: ["/madza/int.jpg"],
    },
  },
  {
    id: "8",
    stock: "DA-1103",
    year: 1991,
    make: "Toyota",
    model: "Pickup",
    trim: "Deluxe XtraCab 4x4",
    price: 2000,
    downPayment: 350,
    mileage: 137100,
    engine: "3.0L V6",
    transmission: "Automatic (4-Speed)",
    drivetrain: "4WD",
    bodyStyle: "Truck",
    exteriorColor: "Dark Gray Metallic",
    color: "Dark Gray Metallic",
    interiorColor: "Gray",
    images: {
      exterior: ["/toyotapic/ext.jpg", "/toyotapic/ext2.jpg"],
      interior: ["/toyotapic/int.jpg"],
    },
  },
  {
    id: "9",
    stock: "DA-1104",
    year: 2006,
    make: "Chevrolet",
    model: "Silverado 1500",
    trim: "LT",
    price: 2800,
    downPayment: 340,
    mileage: 162000,
    engine: "4.8L V8",
    drivetrain: "4WD",
    bodyStyle: "Truck (Short Bed)",
    titleStatus: "Clean, in hand",
    carfaxAvailable: true,
    features: [
      "Cold AC",
      "Power Windows & Locks",
      "Upgraded Shocks",
      "Upgraded Speakers",
      "Touch Screen Radio",
      "Android Auto / Apple CarPlay",
    ],
    color: "Silver",
    images: {
      exterior: ["/chevy/ext.jpg", "/chevy/ext2.jpg"],
      interior: ["/chevy/int.jpg"],
    },
  },
  {
    id: "10",
    stock: "DA-1105",
    year: 2014,
    make: "Infiniti",
    model: "Q50",
    trim: "Premium",
    price: 3000,
    downPayment: 300,
    monthlyPayment: 400,
    mileage: 124000,
    engine: "6-Cylinder",
    drivetrain: "FWD",
    titleStatus: "Clean",
    financingAvailable: true,
    features: [
      "Navigation System",
      "Backup Camera",
      "Heated Seats",
      "Leather Seats",
      "Power Windows",
      "Fully Loaded",
    ],
    color: "Black",
    images: {
      exterior: ["/infinity/ext.jpg", "/infinity/ext2.jpg"],
      interior: ["/infinity/int.jpg"],
    },
  },
  {
    id: "11",
    stock: "DA-1106",
    year: 2012,
    make: "Toyota",
    model: "Camry",
    trim: "",
    price: 2500,
    downPayment: 500,
    engine: "4-Cylinder",
    drivetrain: "FWD",
    titleStatus: "Clean",
    owners: 1,
    accidentHistory: "None reported",
    financingAvailable: true,
    shippingAvailable: true,
    features: [
      "Push Start",
      "Leather Seats",
      "AC Blows Cold",
      "Fully Loaded",
      "Clean Inside & Out",
      "Bluetooth",
    ],
    color: "White",
    images: {
      exterior: ["/camry/ext.jpg", "/camry/ext2.jpg"],
      interior: ["/camry/int.jpg"],
    },
  },
  {
    id: "12",
    stock: "DA-1107",
    year: 2010,
    make: "Toyota",
    model: "Corolla",
    trim: "",
    price: 2000,
    downPayment: 400,
    mileage: 140000,
    engine: "4-Cylinder",
    drivetrain: "FWD",
    titleStatus: "Clean, emissions pass",
    features: [
      "Runs Great",
      "No Oil Leaks",
      "Everything Works Great",
      "AC Blows Cold",
      "Good Tires",
    ],
    color: "Gray",
    images: {
      exterior: ["/corolla/ext.jpg", "/corolla/ext2.jpg"],
      interior: ["/corolla/int.jpg"],
    },
  },
  {
    id: "13",
    stock: "DA-1108",
    year: 2011,
    make: "BMW",
    model: "328i xDrive",
    trim: "",
    price: 2000,
    downPayment: 350,
    mileage: 123000,
    engine: "4-Cylinder",
    drivetrain: "AWD",
    titleStatus: "Clean",
    owners: 1,
    accidentHistory: "None reported",
    features: [
      "Push Start",
      "Leather Seats",
      "AC Blows Cold",
      "Fully Loaded",
      "Clean Inside & Out",
      "Bluetooth",
    ],
    color: "Blue",
    images: {
      exterior: ["/BMW/ext.jpg", "/BMW/ext2.jpg"],
      interior: ["/BMW/int.jpg"],
    },
  },
  {
    id: "14",
    stock: "DA-1109",
    year: 2011,
    make: "BMW",
    model: "X3",
    trim: "28i",
    price: 4000,
    downPayment: 600,
    mileage: 131000,
    drivetrain: "AWD",
    bodyStyle: "SUV",
    titleStatus: "Clean",
    financingAvailable: true,
    features: [
      "Everything Works Perfect",
      "Engine Perfect",
      "Transmission Perfect",
      "Runs & Drives Very Good",
      "Brakes Good",
      "Tires Good",
      "Leather",
      "Navigation",
      "Panoramic Roof",
    ],
    images: {
      exterior: ["/BMWx3/ext.jpg", "/BMWx3/ext2.jpg"],
      interior: ["/BMWx3/int.jpg"],
    },
  },
  {
    id: "15",
    stock: "DA-1110",
    year: 2001,
    make: "Toyota",
    model: "Tacoma",
    trim: "SR5 Regular Cab 4x4",
    price: 2000,
    downPayment: 300,
    transmission: "5-Speed Manual",
    drivetrain: "4WD",
    bodyStyle: "Truck",
    features: [
      "Built for Off-Road & Tough Jobs",
      "Some Performance Modifications",
      "Durable & Long-Lasting",
      "Great for Work, Adventure, or Daily Driving",
    ],
    images: {
      exterior: ["/tacoma/ext.jpg", "/tacoma/ext2.jpg"],
      interior: ["/tacoma/int.jpg"],
    },
  },
  {
    id: "16",
    stock: "DA-1111",
    year: 2015,
    make: "Chrysler",
    model: "200",
    trim: "Limited",
    price: 4500,
    downPayment: 500,
    monthlyPayment: 500,
    mileage: 128767,
    engine: "2.4L 4-Cylinder",
    transmission: "Automatic",
    drivetrain: "FWD",
    exteriorColor: "White",
    interiorColor: "Black Cloth",
    titleStatus: "Clean",
    carfaxAvailable: true,
    financingAvailable: true,
    features: [
      "Reliable & Fuel-Efficient 4-Cylinder Engine",
      "Smooth Automatic Transmission",
      "Spacious Black Cloth Interior",
      "Sleek White Exterior",
      "Great for Commuting or First-Time Buyers",
    ],
    images: {
      exterior: ["/chrysler/ext.jpg", "/chrysler/ext2.jpg"],
      interior: ["/chrysler/int.jpg"],
    },
  },
  {
    id: "17",
    stock: "DA-1112",
    year: 2015,
    make: "Nissan",
    model: "Altima",
    trim: "",
    price: 2500,
    downPayment: 500,
    mileage: 122000,
    drivetrain: "FWD",
    titleStatus: "Clean",
    vin: "1N4AL3APXFC138358",
    shippingAvailable: true,
    financingAvailable: true,
    features: ["No Mechanical or Electrical Faults", "Warranty Available"],
    images: {
      exterior: ["/altima/ext.jpg", "/altima/ext2.jpg"],
      interior: ["/altima/int.jpg"],
    },
  },
  {
    id: "18",
    stock: "DA-1113",
    year: 2012,
    make: "Hyundai",
    model: "Sonata",
    trim: "",
    price: 2000,
    downPayment: 300,
    titleStatus: "Clean, in hand",
    shippingAvailable: true,
    financingAvailable: true,
    features: [
      "Runs & Drives Excellent",
      "Bluetooth Radio",
      "Reservations Accepted",
    ],
    images: {
      exterior: ["/Sonata12/ext.jpg", "/Sonata12/ext2.jpg"],
      interior: ["/Sonata12/int.jpg"],
    },
  },
  {
    id: "19",
    stock: "DA-1114",
    year: 2013,
    make: "Hyundai",
    model: "Sonata",
    trim: "",
    price: 2500,
    downPayment: 500,
    mileage: 150000,
    transmission: "Automatic",
    titleStatus: "Clean",
    shippingAvailable: true,
    financingAvailable: true,
    features: ["Tinted Windows", "Leather Seats"],
    images: {
      exterior: ["/Sonata13/ext.jpg", "/Sonata13/ext2.jpg"],
      interior: ["/Sonata13/int.jpg"],
    },
  },
  {
    id: "20",
    stock: "DA-1115",
    year: 2009,
    make: "Infiniti",
    model: "G35x",
    trim: "",
    price: 3000,
    downPayment: 800,
    mileage: 123000,
    drivetrain: "AWD",
    titleStatus: "Clean",
    shippingAvailable: true,
    financingAvailable: true,
    features: ["No Mechanical Issues", "Ready to Go"],
    images: {
      exterior: ["/Infinityg35x/ext.jpg", "/Infinityg35x/ext2.jpg"],
      interior: ["/Infinityg35x/int.jpg"],
    },
  },
  {
    id: "21",
    stock: "DA-1116",
    year: 1992,
    make: "Honda",
    model: "Accord",
    trim: "EX Sedan",
    price: 1500,
    downPayment: 200,
    mileage: 98800,
    engine: "2.2L I4",
    drivetrain: "FWD",
    transmission: "Manual (5-Speed)",
    exteriorColor: "White",
    interiorColor: "Blue",
    images: {
      exterior: ["/honda/ext.jpg", "/honda/ext2.jpg"],
      interior: ["/honda/int.jpg"],
    },
  },
  {
    id: "22",
    stock: "DA-1117",
    year: 2015,
    make: "Nissan",
    model: "Sentra",
    trim: "SV",
    price: 2000,
    downPayment: 260,
    mileage: 101000,
    shippingAvailable: true,
    financingAvailable: true,
    features: ["Super Clean", "Backup Camera", "Runs Excellent"],
    images: {
      exterior: ["/Nissansentra/ext.jpg", "/Nissansentra/ext2.jpg"],
      interior: ["/Nissansentra/int.jpg"],
    },
  },
  {
    id: "23",
    stock: "DA-1118",
    year: 2016,
    make: "Honda",
    model: "Accord",
    trim: "EX-L",
    price: 3000,
    downPayment: 500,
    mileage: 101000,
    engine: "2.4L I4",
    transmission: "Automatic",
    drivetrain: "FWD",
    titleStatus: "Clean, no accident record",
    financingAvailable: true,
    features: ["Sunroof"],
    images: {
      exterior: ["/HONDAACCORDEXL/ext.jpg", "/HONDAACCORDEXL/ext2.jpg"],
      interior: ["/HONDAACCORDEXL/int.jpg"],
    },
  },
  {
    id: "24",
    stock: "DA-1119",
    year: 2015,
    make: "Toyota",
    model: "Avalon",
    trim: "XLE",
    price: 3000,
    downPayment: 300,
    monthlyPayment: 250,
    mileage: 84500,
    shippingAvailable: true,
    financingAvailable: true,
    features: [
      "Beautiful Interior",
      "Excellent Condition",
      "Super Clean",
      "Runs & Drives Smooth",
      "No Issues",
    ],
    images: {
      exterior: ["/Avalon/ext.jpg", "/Avalon/ext2.jpg"],
      interior: ["/Avalon/int.jpg"],
    },
  },
  {
    id: "25",
    stock: "DA-1120",
    year: 2012,
    make: "Buick",
    model: "LaCrosse",
    price: 3000,
    downPayment: 400,
    monthlyPayment: 350,
    mileage: 63000,
    titleStatus: "Clean",
    shippingAvailable: true,
    financingAvailable: true,
    features: ["No Mechanical Issues"],
    images: {
      exterior: ["/Buik/ext.jpg", "/Buik/ext2.jpg"],
      interior: ["/Buik/int.jpg"],
    },
  },
  {
    id: "26",
    stock: "DA-1121",
    year: 2002,
    make: "Lexus",
    model: "ES 300",
    bodyStyle: "4dr Sedan",
    price: 1000,
    downPayment: 300,
    monthlyPayment: 200,
    mileage: 195000,
    titleStatus: "Clean, no salvage",
    accidentHistory: "No mechanical fault",
    features: ["Fully Loaded", "Runs Great", "Good Condition"],
    images: {
      exterior: ["/lexus/ext.jpg", "/lexus/ext2.jpg"],
      interior: ["/lexus/int.jpg"],
    },
  },
  {
    id: "27",
    stock: "DA-1122",
    year: 2005,
    make: "Cadillac",
    model: "STS",
    price: 1000,
    mileage: 39964,
    engine: "4.6L V8",
    transmission: "Automatic 5-Speed",
    exteriorColor: "Red",
    interiorColor: "Tan",
    images: {
      exterior: ["/Sidalic/ext.jpg", "/Sidalic/ext2.jpg"],
      interior: ["/Sidalic/int.jpg"],
    },
  },
];
export type Service = {
  id: string;
  name: string;
  description: string;
  priceFrom: number;
  duration: string;
  category: "Maintenance" | "Repair" | "Diagnostics";
};

export const services: Service[] = [
  {
    id: "s1",
    name: "Oil & Filter Change",
    description:
      "Full synthetic oil, new filter, and a 21-point courtesy inspection.",
    priceFrom: 49,
    duration: "30 min",
    category: "Maintenance",
  },
  {
    id: "s2",
    name: "Brake Pad & Rotor Service",
    description:
      "Front or rear pads, rotors resurfaced or replaced, fluid check.",
    priceFrom: 189,
    duration: "1.5 hr",
    category: "Repair",
  },
  {
    id: "s3",
    name: "Check Engine Diagnostics",
    description:
      "Full OBD-II scan with a written explanation of what's actually wrong.",
    priceFrom: 89,
    duration: "45 min",
    category: "Diagnostics",
  },
  {
    id: "s4",
    name: "Battery & Alternator Test",
    description: "Load test, charging system check, and replacement if needed.",
    priceFrom: 39,
    duration: "20 min",
    category: "Diagnostics",
  },
  {
    id: "s5",
    name: "Transmission Service",
    description:
      "Fluid and filter exchange to keep shifts smooth and protect the gearbox.",
    priceFrom: 159,
    duration: "1 hr",
    category: "Maintenance",
  },
  {
    id: "s6",
    name: "AC Repair & Recharge",
    description:
      "Leak check, recharge, and component repair to get the cold air back.",
    priceFrom: 119,
    duration: "1 hr",
    category: "Repair",
  },
  {
    id: "s7",
    name: "Tire Rotation & Alignment",
    description:
      "Even out tread wear and keep the car tracking straight down the road.",
    priceFrom: 79,
    duration: "45 min",
    category: "Maintenance",
  },
  {
    id: "s8",
    name: "Pre-Purchase Inspection",
    description:
      "Buying a car elsewhere? We'll check it over before you commit.",
    priceFrom: 69,
    duration: "45 min",
    category: "Diagnostics",
  },
];

export const stats = [
  { label: "Years in Business", value: "14" },
  { label: "Cars Sold", value: "2,800+" },
  { label: "Avg. Bay Turnaround", value: "Same Day" },
  { label: "Customer Rating", value: "4.8/5" },
];
